package com.dof100.morsenotifier;

import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import java.util.Locale;

public class MyRecentAppNotification {
   long timestamp = -1L;
   String b = "";
   String c = "";
   String d = "";
   String e = "";
   String f = "";
   int g = -1;
   int h = -1;
   int i = -1;
   String j = "";

   public void save(Editor var1, int var2) {
      MyLog.log(String.format(Locale.US, "MyRecentAppNotification_.save - notif no %d, package    =%s", var2, this.b));
      StringBuilder var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mDateTime");
      var1.putLong(var3.toString(), this.timestamp);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mPackage");
      var1.putString(var3.toString(), this.b);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mTitle");
      var1.putString(var3.toString(), this.c);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mText");
      var1.putString(var3.toString(), this.d);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mTicker");
      var1.putString(var3.toString(), this.e);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mCategory");
      var1.putString(var3.toString(), this.f);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mID");
      var1.putInt(var3.toString(), this.g);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mAnnounced");
      var1.putInt(var3.toString(), this.h);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_tmpFilter");
      var1.putInt(var3.toString(), this.i);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_tmpAnnouncement");
      var1.putString(var3.toString(), this.j);
   }

   public void load(SharedPreferences var1, int var2) {
      StringBuilder var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mDateTime");
      this.timestamp = var1.getLong(var3.toString(), 0L);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mPackage");
      this.b = var1.getString(var3.toString(), "");
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mTitle");
      this.c = var1.getString(var3.toString(), "");
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mText");
      this.d = var1.getString(var3.toString(), "");
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mTicker");
      this.e = var1.getString(var3.toString(), "");
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mCategory");
      this.f = var1.getString(var3.toString(), "");
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mID");
      this.g = var1.getInt(var3.toString(), -1);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_mAnnounced");
      this.h = var1.getInt(var3.toString(), -1);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_tmpFilter");
      this.i = var1.getInt(var3.toString(), -1);
      var3 = new StringBuilder();
      var3.append("MyRecentAppNotification_");
      var3.append(var2);
      var3.append("_tmpAnnouncement");
      this.j = var1.getString(var3.toString(), "");
      MyLog.log(String.format(Locale.US, "MyRecentAppNotification.load - notif no %d, package    =%s", var2, this.b));
   }
}
